<?php 
    $this->headLink()->appendStylesheet($this->baseUrl('/js/DataTables-1.10.7/media/css/jquery.dataTables.min.css'))
                     ->appendStylesheet($this->baseUrl('/js/DataTables-1.10.7/extensions/TableTools/css/dataTables.tableTools.min.css'))
            ;
    
    $this->headScript()->appendFile($this->baseUrl('/js/DataTables-1.10.7/media/js/jquery.dataTables.min.js'))
                       ->appendFile($this->baseUrl('/js/DataTables-1.10.7/extensions/TableTools/js/dataTables.tableTools.min.js'))
            ;
    $this->headScript()->appendFile($this->baseUrl('/js/view.js'));
?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Categorys List') ?></h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-sortable">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Category Name') ?></th>
                    <th><?php echo $this->translate('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->categorys) {?>
                    <?php foreach ($this->categorys as $category) {?>
                    <tr>
                        <td><?php echo $category['categoryId'] ?></td>
                        <td><?php echo $category['categoryName'] . ' ' . $category['sizeValue'] ?></td>
                        <td>
                            <a href="<?php echo $this->baseUrl()?>/category/edit/id/<?php echo $category['categoryId']?>" class="btn btn-warning"><?php echo $this->translate('Edit') ?></a>
                            <a class="btn btn-danger btn-delete" data-url="<?php echo $this->baseUrl('/category/delete/id/'.$category['categoryId'])?>"><?php echo $this->translate('Delete') ?></a>
                        </td>
                    </tr>
                    <?php }?>
                <?php } else {?>
                    <tr><td colspan="3" class="text-center"><?php echo $this->translate('No categorys yet') ?></td></tr>
                <?php }?>
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-center">
        <a href="<?php echo $this->baseUrl();?>/category/add" class="btn btn-success"><?php echo $this->translate('Add New Category') ?></a>
    </div>
</div>

<!-- Delete Import Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body text-center"><?php echo $this->translate('Are you sure you want to DELETE category?') ?></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('No') ?></button>
                <a href="#" class="btn btn-danger"><?php echo $this->translate('Yes') ?></a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        var table = $(".table-sortable").DataTable({
                        language: {
                            "url": "//cdn.datatables.net/plug-ins/1.10.7/i18n/Arabic.json"
                        },
                        pageLength: 25,
                        //dom: 'C<"clear">lfrtip',
                        //dom: 'T<"clear">lfrtip',
                        /*tableTools: {
                            "sSwfPath": "<?php echo $this->baseUrl('/js/DataTables-1.10.7/extensions/TableTools/swf/copy_csv_xls_pdf.swf')?>",
                            "aButtons": [ 
                                {
                                    "sExtends": "copy",
                                    "sButtonText": "نسخ"
                                },
                                {
                                    "sExtends": "print",
                                    "sButtonText": "طباعة"
                                } 
                            ]
                        }*/
                    });
    });
</script>