<?php 
$this->headScript()->appendFile($this->baseUrl('/js/view.js'));
?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Suppliers List') ?></h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Name') ?></th>
                    <th><?php echo $this->translate('Address') ?></th>
                    <th><?php echo $this->translate('Phone') ?></th>
                    <th><?php echo $this->translate('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->suppliers) {?>
                    <?php foreach ($this->suppliers as $supplier) {?>
                    <tr>
                        <td><?php echo $supplier['supplierId'] ?></td>
                        <td><?php echo $supplier['supplierName'] ?></td>
                        <td><?php echo $supplier['supplierAddress'] ?></td>
                        <td><?php echo $supplier['supplierPhone'] ?></td>
                        <td>
                            <a href="<?php echo $this->baseUrl()?>/supplier/edit/id/<?php echo $supplier['supplierId']?>" class="btn btn-warning"><?php echo $this->translate('Edit') ?></a>
                            <a class="btn btn-danger btn-delete" data-url="<?php echo $this->baseUrl('/supplier/delete/id/'.$supplier['supplierId'])?>"><?php echo $this->translate('Delete') ?></a>
                        </td>
                    </tr>
                    <?php }?>
                <?php } else {?>
                    <tr><td colspan="6" class="text-center"><?php echo $this->translate('No suppliers yet') ?></td></tr>
                <?php }?>
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-center">
        <a href="<?php echo $this->baseUrl();?>/supplier/add" class="btn btn-success"><?php echo $this->translate('Add New Supplier') ?></a>
    </div>
</div>

<!-- Delete Import Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body text-center"><?php echo $this->translate('Are you sure you want to DELETE supplier?') ?></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('No') ?></button>
                <a href="#" class="btn btn-danger"><?php echo $this->translate('Yes') ?></a>
            </div>
        </div>
    </div>
</div>