<?php 
    $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap-datetimepicker.min.css'));
    
    $this->headScript()->appendFile($this->baseUrl('/js/moment-2.7.0.min.js'))
                       ->appendFile($this->baseUrl('/js/bootstrap-datetimepicker.min.js'))
                       ->appendFile($this->baseUrl('/js/bootstrap-datetimepicker.ar.js'))
                       ->appendFile($this->baseUrl('/js/jquery.autocomplete.js'))
                       ->appendFile($this->baseUrl('/js/json2.min.js'))
                       ->appendFile($this->baseUrl('/js/import.js'));
?>

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Add New Import') ?></h3>
    </div>
    <div class="panel-body">
        <table class="table table-bordered text-center table-category">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center"><?php echo $this->translate('Category Name') ?></th>
                    <th class="text-center"><?php echo $this->translate('Quantity') ?></th>
                    <th class="text-center col-buy-price"><?php echo $this->translate('Buy Price') ?></th>
                    <th class="text-center"><?php echo $this->translate('Sell Price') ?></th>
                    <th class="text-center"></th>
                </tr>
            </thead>
            <tbody>
                <tr class="category-row">
                    <td class="row-id">1</td>
                    <td>
                        <input type="text" name="category" id="category" class="category-name">
                        <span class="fa fa-pencil fa-fw edit-category hidden" title="<?php echo $this->translate('Change category') ?>"></span>
                    </td>
                    <td><input type="text" name="quantity" id="quantity" class="category-value number"></td>
                    <td class="col-buy-price"><input type="text" name="buyPrice" id="buyPrice" class="category-value number float"></td>
                    <td><input type="text" name="sellPrice" id="sellPrice" class="category-value number float"></td>
                    <td><span class="fa fa-remove fa-fw remove-category" title="<?php echo $this->translate('Remove category') ?>"></span></td>
                </tr>
                <tr class="last-row">
                    <td></td>
                    <td>
                        <button id="addcategory" class="btn btn-success" data-role="button">
                            <i class="fa fa-plus-circle fa-fw"></i> <?php echo $this->translate('Add Category to Import') ?>
                        </button>
                        <button id="addnewcategory" class="btn btn-info" data-role="button">
                            <i class="fa fa-plus-circle fa-fw"></i> <?php echo $this->translate("Add Category Doesn't Exist") ?>
                        </button>
                    </td>
                    <td></td>
                    <td class="col-buy-price"></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <div>
            <input type="checkbox" name="billPercentage" id="billPercentage"/> 
            <label for="billPercentage"><?php echo $this->translate('Benefit as Bill Percentage') ?></label>
        </div>
        <?php echo $this->form ?>
    </div>
    <div class="panel-footer text-left">
        <a href="<?php echo $this->baseUrl('/import');?>" class="btn btn-default"><?php echo $this->translate('Back to Import List') ?></a>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="addNewCategoryModal" tabindex="-1" aria-labelledby="addNewCategoryModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('Add New Category') ?></h3>
                </div>
            </div>
            <div class="modal-body">
                <div id="success-msg" class="alert alert-success hidden" role="alert"></div>
                <?php echo $this->categroyForm ?>
            </div>
        </div>
    </div>
</div>

<table class="hidden new-row">
    <tr class="category-row">
        <td class="row-id">1</td>
        <td>
            <input type="text" name="category" id="category" class="category-name">
            <span class="fa fa-pencil fa-fw edit-category hidden" title="<?php echo $this->translate('Change category') ?>"></span>
        </td>
        <td><input type="text" name="quantity" id="quantity" class="category-value number"></td>
        <td class="col-buy-price"><input type="text" name="buyPrice" id="buyPrice" class="category-value number float"></td>
        <td><input type="text" name="sellPrice" id="sellPrice" class="category-value number float"></td>
        <td><span class="fa fa-remove fa-fw remove-category" title="<?php echo $this->translate('Remove category') ?>"></span></td>
    </tr>
</table>