<tr class="category-row">
    <td class="row-id"></td>
    <td><input type="text" name="category" id="category" class="category-name"></td>
    <td><input type="text" name="quantity" id="quantity" class="category-value"></td>
    <td class="col-buy-price"><input type="text" name="buyPrice" id="buyPrice" class="category-value"></td>
    <td><input type="text" name="sellPrice" id="sellPrice" class="category-value"></td>
    <td><a href="#" style="color:red" class="remove-category"><i class="fa fa-remove fa-fw"></i></a></td>
</tr>