<?php 
    $this->headLink()->appendStylesheet($this->baseUrl('/css/bootstrap-datetimepicker.min.css'));
    
    $this->headScript()->appendFile($this->baseUrl('/js/moment-2.7.0.min.js'))
                       ->appendFile($this->baseUrl('/js/bootstrap-datetimepicker.min.js'))
                       ->appendFile($this->baseUrl('/js/bootstrap-datetimepicker.ar.js'))
                       //->appendFile($this->baseUrl('/js/jquery.autocomplete.js'))
                       //->appendFile($this->baseUrl('/js/json2.min.js'))
                       //->appendFile($this->baseUrl('/js/import.js'))
                       ;
?>

<div class="panel panel-warning">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Edit Import') ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->form ?>
    </div>
    <div class="panel-footer text-center">
        <a href="<?php echo $this->baseUrl();?>/import" class="btn btn-default"><?php echo $this->translate('Back to Import List') ?></a>
    </div>
</div>