<?php 
$this->headScript()->appendFile($this->baseUrl('/js/view.js'));
?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Imports List') ?></h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Supplier') ?></th>
                    <th><?php echo $this->translate('Order ID') ?></th>
                    <th><?php echo $this->translate('Date') ?></th>
                    <th><?php echo $this->translate('Total Price') ?></th>
                    <th><?php echo $this->translate('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->imports) {?>
                    <?php foreach ($this->imports as $import) {?>
                    <tr>
                        <td><?php echo $import['importId'] ?></td>
                        <td><?php echo ($import['supplierName'])? $import['supplierName'] : '-' ?></td>
                        <td><?php echo ($import['importOrder'])? $import['importOrder'] : '-' ?></td>
                        <td><?php echo $import['importDate'] ?></td>
                        <td><?php echo ($import['importDiscount'])? $import['totalSellPrice'] : $import['totalBuyPrice'] ?></td>
                        <td>
                            <a href="#" class="btn btn-info btn-import-view" data-id="<?php echo $import['importId']?>"><?php echo $this->translate('View') ?></a>
                            <a href="<?php echo $this->baseUrl()?>/import/edit/id/<?php echo $import['importId']?>" class="btn btn-warning"><?php echo $this->translate('Edit') ?></a>
                            <a href="<?php echo $this->baseUrl()?>/import/delete/id/<?php echo $import['importId']?>" class="btn btn-danger"><?php echo $this->translate('Delete') ?></a>
                        </td>
                    </tr>
                    <?php }?>
                <?php } else {?>
                    <tr><td colspan="6" class="text-center"><?php echo $this->translate('No imports yet') ?></td></tr>
                <?php }?>
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-center">
        <a href="<?php echo $this->baseUrl();?>/import/add" class="btn btn-success"><?php echo $this->translate('Add New Import') ?></a>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="viewImportModal" tabindex="-1" role="dialog" aria-labelledby="viewImportModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
            </div>
        </div>
    </div>
</div>