<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Add New User') ?></h3>
    </div>
    <div class="panel-body">
        <?php echo $this->form ?>
    </div>
    <div class="panel-footer text-center">
        <a href="<?php echo $this->baseUrl();?>/user" class="btn btn-default"><?php echo $this->translate('Back to User List') ?></a>
    </div>
</div>