<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('Users List') ?></h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('Full Name') ?></th>
                    <th><?php echo $this->translate('Username') ?></th>
                    <th><?php echo $this->translate('Role') ?></th>
                    <th><?php echo $this->translate('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->users) {?>
                    <?php foreach ($this->users as $user) {?>
                    <tr>
                        <td><?php echo $user['userId'] ?></td>
                        <td><?php echo $user['userFullname'] ?></td>
                        <td><?php echo $user['userName'] ?></td>
                        <td><?php echo $user['roleName'] ?></td>
                        <td>
                            <a href="<?php echo $this->baseUrl()?>/user/edit/id/<?php echo $user['userId']?>" class="btn btn-warning"><?php echo $this->translate('Edit') ?></a>
                            <a href="<?php echo $this->baseUrl()?>/user/delete/id/<?php echo $user['userId']?>" class="btn btn-danger"><?php echo $this->translate('Delete') ?></a>
                        </td>
                    </tr>
                    <?php }?>
                <?php } else {?>
                    <tr><td colspan="3" class="text-center"><?php echo $this->translate('No users yet') ?></td></tr>
                <?php }?>
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-center">
        <a href="<?php echo $this->baseUrl();?>/user/add" class="btn btn-success"><?php echo $this->translate('Add New User') ?></a>
    </div>
</div>